const CHUNK_PUBLIC_PATH = "server/app/about/page.js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_66bdff._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__ea5163._.js");
runtime.loadChunk("server/chunks/ssr/app_db13a2._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_fa_index_mjs_a1beb0._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_lib_b806b5._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_ba55cd._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__da064a._.js");
runtime.loadChunk("server/chunks/ssr/[root of the server]__b78b0f._.css");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_client_components_not-found-error_b76de5.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_io5_index_mjs_1653de._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_react-icons_bi_index_mjs_fdc4ea._.js");
runtime.loadChunk("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_068f12.js");
runtime.loadChunk("server/chunks/ssr/_9a8279._.js");
runtime.getOrInstantiateRuntimeModule("[project]/.next-internal/server/app/about/page/actions.js [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/next/dist/esm/build/templates/app-page.js?page=/about/page { METADATA_0 => \"[project]/app/favicon.ico.mjs { IMAGE => \\\"[project]/app/favicon.ico [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript, Next.js server component)\", MODULE_1 => \"[project]/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", MODULE_2 => \"[project]/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", MODULE_3 => \"[project]/app/about/page.tsx [app-rsc] (ecmascript, Next.js server component)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH).exports;
